name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install torch>=1.6.0 transformers>=4.33.0 datasets>=2.19.0 accelerate>=0.20.1 sentence_transformers peft pytest

      - name: Run tests
        run: |
          pytest tests